name: dispatch
on:
  workflow_dispatch:
    inputs:
      skip:
        description: 'Will you skip the 1st job?'
        required: true
        default: 'no'
jobs:
  job_1st:
    runs-on: ubuntu-20.04
    if: github.event.inputs.skip == 'no'
    steps:
      - run: echo "1st job!"
  job_2nd:
    runs-on: ubuntu-20.04
    needs: job_1st
    if: ${{ !failure() && !cancelled() }}
    steps:
      - run: echo "2nd job!"
  job_3rd:
    runs-on: ubuntu-20.04
    needs: job_2nd
    if: success()
    steps:
      - run: echo "3rd job!"
