name: dispatch
on:
  workflow_dispatch:
jobs:
  job_1st:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - run: echo "1st job!"
      - name: Create tag
        run: |
          TAG="$(date +%Y%m%d-%H%M)-$(git rev-parse --short=10 HEAD)"
          echo "::set-output name=tag::v${TAG}"
        id: create-tag
  job_2nd:
    runs-on: ubuntu-20.04
    needs: job_1st
    steps:
      - run: echo "2nd job!"
      - run: echo ${{ needs.job_1st.outputs.tag }}
  job_3rd:
    runs-on: ubuntu-20.04
    needs: job_2nd
    steps:
      - run: echo "3rd job!"
